---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/nogalesd/public_html/app.nogalesdelaflorida.com/
    - /bin/rsync -r -av --exclude=".*" -u /home2/nogalesd/repositories/appnogales/ $DEPLOYPATH
