---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/nogalesd/public_html/app.nogalesdelaflorida.com/
    - /bin/rsync -r -u/home2/nogalesd/repositories/appnogales/css/ $DEPLOYPATH
    - /bin/rsync -r -u/home2/nogalesd/repositories/appnogales/img/ $DEPLOYPATH
    - /bin/rsync -r -u/home2/nogalesd/repositories/appnogales/js/ $DEPLOYPATH
    - /bin/rsync -u/home2/nogalesd/repositories/appnogales/index.html $DEPLOYPATH
    - /bin/rsync -u/home2/nogalesd/repositories/appnogales/style.css $DEPLOYPATH